---
author:
  email: 
  name: An Author
  twitter: 
  url: 
baseurl: "/black-jacob-test-hosted-2017-03-23"
collections:
  annotations:
    output: true
    permalink: "/annotations/:path/"
  volume_pages:
    output: true
    permalink: "/pages/:path/"
defaults:
- scope:
    path: ''
    type: volume_pages
  values:
    layout: volume_page
    short_label: p.
    deep_zoom: true
    extra_js:
    - volume-page.js
    - hammer.min.js
    - deepzoom.js
    - openseadragon.min.js
- scope:
    path: ''
    type: annotations
  values:
    layout: annotation
description: An annotated digital edition created with <a href="http://readux.library.emory.edu/">Readux</a>
gems:
- jekyll-sitemap
homepage_image: https://readux.library.emory.edu/books/emory:b5h9g/pages/emory:gnfvk/single-page/
image_size:
  page:
    width: 719
    height: 1000
  thumbnail:
    width: 215
    height: 300
  small-thumbnail:
    width: 71
    height: 100
permalink: pretty
publication_info:
  title: '"Black Jacob," a monument of grace  the life of Jacob Hodges, an African
    Negro, who died in Canandaigua, N.Y., February 1842 , an annotated digital edition'
  date: '2017'
  author: Eddy, A. D. (Ansel Doane), 1798-1875.
  editors:
  - Sara Palmer
  tei_xml: tei.xml
show_annotation_author: true
source_info:
  title: '"Black Jacob," a monument of grace  the life of Jacob Hodges, an African
    Negro, who died in Canandaigua, N.Y., February 1842 '
  author: Eddy, A. D. (Ansel Doane), 1798-1875.
  date: '2011'
  url: https://readux.library.emory.edu/books/emory:b5h9g/
  pdf_url: https://readux.library.emory.edu/books/emory:b5h9g/pdf/#page=2
  via_readux: true
tagline: ", an annotated digital edition"
title: '"Black Jacob," a monument of grace  the life of Jacob Hodges, an African Negro,
  who died in Canandaigua, N.Y., February 1842 '
url: https://sarepal.github.io
version: 0.7
